// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Element is one thing on the canvas.
 * 
 * The known fields are parsed; **the whole original object is kept in Raw**.
 * A newer Bava will write element types and keys this one does not know, and
 * dropping them destroys work silently — unrecoverable by the time anyone
 * notices. Writing an element means writing Raw back with the known fields
 * merged over it.
 */
export interface Element {
    "id": string;
    "type": string;
    "x": number;
    "y": number;
    "w": number;
    "h": number;
    "z": number;
}

/**
 * Scene is the canvas.
 */
export interface Scene {
    "version": number;
    "elements": Element[] | null;
}
