// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExportService writes an exported picture to disk.
 * 
 * The picture itself is drawn in the frontend, which owns the canvas: this
 * side only puts bytes where the user asked. It is deliberately not part of
 * FileService, which is about the user's documents; an export is a copy, and
 * nothing here touches the document or its stamp.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Save writes base64-encoded bytes to path, returning a message the user can
 * act on, or "" when it worked.
 * 
 * The contents arrive base64-encoded because the bridge is JSON: raw bytes
 * would cross as an array of numbers, several times the size of the image.
 * The write is the same atomic temp-and-rename a document save uses, so a
 * failure never leaves half a PNG where a whole one used to be, and a missing
 * folder is an error rather than something silently created.
 */
export function Save(path: string, contentsBase64: string): $CancellablePromise<string> {
    return $Call.ByID(15992374, path, contentsBase64);
}
