// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService is the file surface. It stays thin: read, write, and tell the
 * caller whether the file moved underneath them. Everything about *what* a
 * file contains lives in internal/format.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as format$0 from "../format/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChangedOnDisk reports whether the file moved underneath the editor.
 */
export function ChangedOnDisk(path: string, stamp: store$0.Stamp): $CancellablePromise<boolean> {
    return $Call.ByID(1288114517, path, stamp);
}

/**
 * ChooseFileToOpen shows the native open dialog.
 * 
 * Cancelling is not an error: an empty path means the user changed their mind,
 * which is a normal outcome and not something to report as a failure.
 */
export function ChooseFileToOpen(): $CancellablePromise<$models.DialogResult> {
    return $Call.ByID(504373913);
}

/**
 * ChooseFileToSave shows the native save dialog.
 */
export function ChooseFileToSave(suggestedName: string): $CancellablePromise<$models.DialogResult> {
    return $Call.ByID(931060408, suggestedName);
}

/**
 * ChooseMedia shows the native open dialog for images, videos or any file
 * ("image", "video" or "file"), several at once. Cancelling returns no paths
 * and no error.
 */
export function ChooseMedia(kind: string): $CancellablePromise<$models.PathsResult> {
    return $Call.ByID(702476426, kind);
}

/**
 * ClipboardImage is the clipboard's image as PNG in base64, for a paste into
 * the Document; empty when the clipboard holds no image. Wails reads text
 * only, so the image comes through here.
 */
export function ClipboardImage(): $CancellablePromise<string> {
    return $Call.ByID(1963423996);
}

/**
 * FileDetails reads a file card's details from the file, inside a folder the
 * user opened. A file that is not there is no error: its card says so.
 */
export function FileDetails(root: string, rel: string): $CancellablePromise<$models.FileDetailsResult> {
    return $Call.ByID(2439111753, root, rel);
}

/**
 * Open reads and parses a file.
 */
export function Open(path: string): $CancellablePromise<$models.OpenResult> {
    return $Call.ByID(1348112483, path);
}

/**
 * OpenFile opens a document of a folder the user opened in its own app, as
 * a file card's click does; anything else is shown in its folder (see
 * documents). A link on the way to it is refused. An error is its message.
 */
export function OpenFile(root: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(2294496701, root, rel);
}

/**
 * Save writes a file, replacing only the canvas block within it.
 */
export function Save(path: string, source: string, scene: format$0.Scene): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(408803850, path, source, scene);
}

/**
 * SaveSettings writes the user's preferences.
 */
export function SaveSettings(settings: config$0.Settings): $CancellablePromise<string> {
    return $Call.ByID(1567707823, settings);
}

/**
 * Settings returns the user's preferences, falling back to defaults.
 * 
 * The frontend reads these once at start-up.
 */
export function Settings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(267895474);
}
