// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService is the frontend's way into Bava's log. Nothing it does leaves
 * the machine: Diagnostics returns text for the user to copy, and
 * OpenLogsFolder opens a local folder.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Diagnostics returns a plain-text report for the user to copy: the build,
 * the platform, and the session's recent log lines, already redacted.
 */
export function Diagnostics(userAgent: string): $CancellablePromise<string> {
    return $Call.ByID(2577341313, userAgent);
}

/**
 * OpenLogsFolder reveals the log folder in the platform's file manager.
 * Returns an error message, or "" on success.
 */
export function OpenLogsFolder(): $CancellablePromise<string> {
    return $Call.ByID(3530122168);
}

/**
 * Report writes a frontend error to the log.
 */
export function Report(entry: $models.LogEntry): $CancellablePromise<void> {
    return $Call.ByID(2792350165, entry);
}

/**
 * SetVerbose switches debug detail on or off and saves the preference.
 * Returns an error message, or "" on success.
 */
export function SetVerbose(on: boolean): $CancellablePromise<string> {
    return $Call.ByID(3465701401, on);
}

/**
 * TakeNotices returns pending notices once; a second call returns none.
 */
export function TakeNotices(): $CancellablePromise<$models.Notice[] | null> {
    return $Call.ByID(3481836997);
}
