// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MenuService owns the native menu bar and keeps it in step with the frontend.
 * 
 * It is registered with the application before the menu exists, and built by
 * InstallMenu afterwards: native role items read the application's name when they
 * are constructed, so they cannot be made before application.New.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as menu$0 from "./menu/models.js";

/**
 * SetState makes checks, enabled items and recent files match the frontend.
 * Before InstallMenu it does nothing: there is no menu to update yet.
 */
export function SetState(state: menu$0.State): $CancellablePromise<void> {
    return $Call.ByID(1869122623, state);
}
