// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as format$0 from "../format/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * DialogResult is a chosen path, or an empty one when the user cancelled.
 */
export interface DialogResult {
    "path": string;
    "error": string;
}

/**
 * Entry is a file or folder in a workspace.
 */
export interface Entry {
    "name": string;
    "path": string;
    "isDir": boolean;
}

/**
 * ListResult is a workspace listing.
 */
export interface ListResult {
    "entries": Entry[] | null;
    "error": string;
}

/**
 * OpenResult is a file, parsed.
 * 
 * Problems the user can act on — a missing file, a permission denial, a
 * malformed canvas block — come back in Error rather than as a failed call,
 * the same way compile diagnostics do. A returned error means the request
 * itself was malformed.
 */
export interface OpenResult {
    "path": string;
    "source": string;
    "diagrams": { [_ in string]?: string } | null;
    "scene": format$0.Scene;
    "stamp": store$0.Stamp;
    "error": string;
}

/**
 * SaveResult reports a completed write.
 */
export interface SaveResult {
    "path": string;
    "stamp": store$0.Stamp;
    "error": string;
}
