// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as format$0 from "../format/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as space$0 from "../space/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * DialogResult is a chosen path, or an empty one when the user cancelled.
 */
export interface DialogResult {
    "path": string;
    "error": string;
}

/**
 * LogEntry is an error the frontend reports. It carries the error's kind and
 * stack frames, never its message: JavaScript messages quote input (a JSON
 * syntax error shows the text it choked on), and a thrown value can be anything.
 */
export interface LogEntry {
    "level": string;

    /**
     * Kind is the error's constructor name ("TypeError"), or the thrown
     * value's type.
     */
    "kind": string;
    "stack": string;

    /**
     * Source says where it was caught: "window", "rejection", "boundary", or a
     * module name.
     */
    "source": string;
}

/**
 * Notice is something the user should be told once.
 */
export interface Notice {
    "kind": string;

    /**
     * Session is the log file of the session concerned, when there is one.
     */
    "session": string;
}

/**
 * OpResult is what an operation made: the item's new path, a Trash item's id,
 * or a renamed Space's new root.
 */
export interface OpResult {
    "path": string;
    "id": string;
    "root": string;
    "error": string;
    "code": string;
}

/**
 * OpenResult is a file, parsed.
 * 
 * Problems the user can act on (a missing file, a permission denial, a
 * malformed canvas block) come back in Error rather than as a failed call,
 * the same way compile diagnostics do. A returned error means the request
 * itself was malformed.
 */
export interface OpenResult {
    "path": string;
    "source": string;
    "diagrams": { [_ in string]?: string } | null;
    "scene": format$0.Scene;
    "stamp": store$0.Stamp;
    "error": string;
}

/**
 * Operation is one change to a Space. Kind is createPage, createFolder,
 * rename, move, duplicate, trash, restore, deleteForever, emptyTrash,
 * renameSpace or setPageWidth; the other fields are what it needs.
 */
export interface Operation {
    "kind": string;
    "path": string;
    "folder": string;
    "name": string;

    /**
     * Index is where in Folder a move lands; -1 for the end.
     */
    "index": number;
    "id": string;
    "width": string;
}

/**
 * SaveResult reports a completed write.
 */
export interface SaveResult {
    "path": string;
    "stamp": store$0.Stamp;
    "error": string;
}

/**
 * SpaceInfo is an opened Space.
 */
export interface SpaceInfo {
    "root": string;
    "name": string;
    "pageWidth": string;
    "error": string;

    /**
     * Code names a refusal the frontend words itself (space.Code); "" for
     * any other failure, whose Error is shown as it is.
     */
    "code": string;
}

/**
 * SpaceList is one folder of a Space, in the Space's order.
 */
export interface SpaceList {
    "entries": space$0.Entry[] | null;
    "error": string;
    "code": string;
}

/**
 * TrashList is the Space's Trash and its total size in bytes.
 */
export interface TrashList {
    "items": space$0.TrashItem[] | null;
    "size": number;
    "error": string;
    "code": string;
}
