// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RenderService is the one render surface. Resist adding a second: a preview,
 * export or thumbnail renderer would drift from this one and produce output
 * that differs from what the user saw.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as render$0 from "../render/models.js";

/**
 * Render compiles D2 source and returns the SVG, any diagnostics, and the map
 * from SVG element id to source position.
 * 
 * A returned error means the request was malformed. Source that does not
 * compile is not an error: it comes back in Result.Errors, and the frontend
 * keeps the last good diagram on screen.
 */
export function Render(source: string, opts: render$0.Options): $CancellablePromise<render$0.Result> {
    return $Call.ByID(188839229, source, opts);
}
