// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SpaceService is a Space's file surface (docs/ipc.md, "SpaceService"): open
 * a folder as a Space, list it, and change it through one Apply, so the bound
 * surface stays small. Problems the user can act on come back in Error.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply runs one operation on a Space.
 */
export function Apply(root: string, op: $models.Operation): $CancellablePromise<$models.OpResult> {
    return $Call.ByID(2192293281, root, op);
}

/**
 * Attachments lists the files of the Space's attachments folder, for Media.
 * Which pages use each is worked out by the page, from the pages' text.
 */
export function Attachments(root: string): $CancellablePromise<$models.AttachmentList> {
    return $Call.ByID(299153851, root);
}

/**
 * ChooseFolder shows the native folder picker, which can also make a new
 * folder, titled as the frontend words it. An empty path means the user
 * cancelled.
 */
export function ChooseFolder(title: string): $CancellablePromise<$models.DialogResult> {
    return $Call.ByID(1240358610, title);
}

/**
 * Create makes a new folder in parent, named as the user typed, and opens it
 * as a Space.
 */
export function Create(parent: string, name: string): $CancellablePromise<$models.SpaceInfo> {
    return $Call.ByID(579321623, parent, name);
}

/**
 * FetchCard reads a web page's details for a card, when the user pastes its
 * link or asks for its details again. The icon and picture are saved in the
 * Space's attachments, named by the site; outside a Space (root "") they are
 * not kept.
 */
export function FetchCard(root: string, address: string): $CancellablePromise<$models.CardDetails> {
    return $Call.ByID(728531723, root, address);
}

/**
 * Index lists every page in a Space, with each page's text when withText is
 * set: the frontend reads links with the Document's own reader, so what a
 * link is never differs between an open page and the others.
 */
export function Index(root: string, withText: boolean): $CancellablePromise<$models.SpaceIndex> {
    return $Call.ByID(3863460661, root, withText);
}

/**
 * List lists one folder of a Space.
 */
export function List(root: string, folder: string): $CancellablePromise<$models.SpaceList> {
    return $Call.ByID(3073914039, root, folder);
}

/**
 * Open opens a folder as a Space, creating .bava/space.json when missing.
 */
export function Open(dir: string): $CancellablePromise<$models.SpaceInfo> {
    return $Call.ByID(1337079187, dir);
}

/**
 * Reveal shows the Space's folder, or with a path, that item selected in its
 * folder, in the platform's file manager. A zero Problem means it worked.
 */
export function Reveal(root: string, path: string): $CancellablePromise<$models.Problem> {
    return $Call.ByID(1424773362, root, path);
}

/**
 * Trash lists the Space's Trash, most recently deleted first.
 */
export function Trash(root: string): $CancellablePromise<$models.TrashList> {
    return $Call.ByID(2780375675, root);
}
