// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Scenario is a smoke walk: the folder picker's answers and the media
 * picker's (each a list of files, empty for a cancel), in the order the
 * pickers are shown, and the steps.
 */
export interface Scenario {
    "name": string;
    "folders"?: string[] | null;
    "files"?: (string[] | null)[] | null;
    "steps": Step[] | null;
}

/**
 * Step is one thing the driver does in the page. Target is a CSS selector,
 * or a menu command id for "menu"; Text is what to type, the key to press, or
 * the text a "wait" expects inside its target.
 */
export interface Step {
    "do": string;
    "target"?: string;
    "text"?: string;
    "name"?: string;
    "from"?: number[] | null;
    "to"?: number[] | null;
    "timeoutMs"?: number;
}
