// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is bound to the page in a -tags e2e build: the page's driver asks
 * it for the scenario, for screenshots, and reports how the run ended.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Done records how the run ended, PASS or FAIL with the reason, and quits
 * with a matching exit code. An empty failure means it passed.
 */
export function Done(failure: string): $CancellablePromise<void> {
    return $Call.ByID(2576671742, failure);
}

/**
 * Scenario is the walk the page runs.
 */
export function Scenario(): $CancellablePromise<$models.Scenario> {
    return $Call.ByID(1533288220);
}

/**
 * Shot saves a screenshot of the screen, numbered in the order taken.
 * Returns an error message, or "".
 */
export function Shot(name: string): $CancellablePromise<string> {
    return $Call.ByID(2225783022, name);
}
