// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings are the values a user can change.
 * 
 * The render values started life as compile-time constants in Milestone 1 and
 * are named here so a change is a preference rather than a rebuild.
 */
export interface Settings {
    /**
     * DebounceMS is the quiet period before a render is issued. 250 is the
     * measured value: dagre 12ms, elk 7ms, TALA 96ms on a ~25 node diagram.
     */
    "debounceMs": number;

    /**
     * LayoutEngine is the default for diagrams that do not name one.
     */
    "layoutEngine": string;

    /**
     * Autosave is when an open, titled document is written without being
     * asked: never, a quiet period after the last change, or when the window
     * loses focus. The names follow VS Code's files.autoSave.
     */
    "autosave": string;

    /**
     * AutosaveDelayMS is the quiet period for AutosaveAfterDelay.
     */
    "autosaveDelayMs": number;
}
