// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * State is what the frontend reports so the menu reflects the app.
 */
export interface State {
    "viewMode": string;
    "showsFiles": boolean;
    "showsAI": boolean;
    "theme": string;
    "tool": string;
    "hasSelection": boolean;
    "recents": string[] | null;
}
