// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * State is what the frontend reports so the menu reflects the app.
 */
export interface State {
    "viewMode": string;
    "showsFiles": boolean;
    "showsAI": boolean;
    "theme": string;
    "tool": string;
    "hasSelection": boolean;

    /**
     * CanPasteStyles reports a style copied with Copy Styles.
     */
    "canPasteStyles": boolean;

    /**
     * HasLocked reports at least one locked element in the scene.
     */
    "hasLocked": boolean;

    /**
     * HasDocument reports a file open, which is what Export needs.
     */
    "hasDocument": boolean;
    "recents": string[] | null;
}
