// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Stamp is what a file looked like when it was read.
 * 
 * Size and modification time, which is enough to prompt and cheap enough to
 * check whenever the window regains focus. A content hash would be exact and
 * would mean reading every open file on every focus change.
 */
export interface Stamp {
    "size": number;

    /**
     * ModifiedUnixNano crosses to the frontend as a decimal string: its 19
     * digits do not survive a JavaScript number, which rounded it and made
     * every file look changed on disk.
     */
    "modifiedUnixNano": `${number}`;
}
