// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Stamp is what a file looked like when it was read.
 * 
 * Size and modification time, which is enough to prompt and cheap enough to
 * check whenever the window regains focus. A content hash would be exact and
 * would mean reading every open file on every focus change.
 */
export interface Stamp {
    "size": number;
    "modifiedUnixNano": number;
}
