// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Diagnostic is one compiler complaint about the source.
 */
export interface Diagnostic {
    "message": string;
    "from": number;
    "to": number;
    "line": number;
}

/**
 * Options selects how a diagram is rendered. It is an options struct rather
 * than a widening parameter list because every field here crosses the IPC
 * boundary, and adding one must not change the binding's signature.
 */
export interface Options {
    /**
     * Engine names the layout algorithm. Empty selects layout.DefaultEngine.
     */
    "engine": string;

    /**
     * Theme carries the diagram colours. Nil renders D2's own defaults, which
     * is what every golden committed before theming was added expects.
     */
    "theme"?: Theme | null;
}

/**
 * Result is the whole response to a render request.
 */
export interface Result {
    /**
     * SVG is the rendered diagram, with no XML declaration so it can be
     * injected directly into the DOM node the canvas owns. Empty when the
     * source did not compile.
     */
    "svg": string;

    /**
     * Errors carries compile diagnostics. A failed compile is an expected
     * state, not a failed call: the caller keeps the last good diagram on
     * screen and shows these.
     */
    "errors": Diagnostic[] | null;

    /**
     * NodeMap maps SVG element id to the source that produced it.
     */
    "nodeMap": { [_ in string]?: Span } | null;
}

/**
 * Span locates something in the source.
 * 
 * From and To are offsets in UTF-16 code units, which is how JavaScript and
 * CodeMirror index a document — not byte offsets. Line is 1-indexed; D2's own
 * lines are 0-indexed and the conversion happens here, once, so nothing
 * downstream repeats it.
 */
export interface Span {
    "from": number;
    "to": number;
    "line": number;
}

/**
 * Theme carries the diagram colours for a render.
 * 
 * The token layer in `frontend/src/styles/tokens/_color.scss` is the source of
 * truth for the values; Go holds the mapping onto D2's palette and no copy of
 * the palette itself. A diagram's SVG does not inherit CSS, so a theme change
 * has to travel this path or the canvas keeps the old colours while the chrome
 * changes around it.
 */
export interface Theme {
    "background": string;
    "containerFill": string;
    "nodeFill": string;
    "nodeStroke": string;
    "label": string;
    "edge": string;
    "edgeLabel": string;
}
