// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Diagnostic is one compiler complaint about the source.
 */
export interface Diagnostic {
    "message": string;
    "from": number;
    "to": number;
    "line": number;
}

/**
 * Layout is the geometry the canvas builds shapes from.
 * 
 * It is what the diagram *is*, not how D2 painted it: position, size, label,
 * nesting and the route of each connection. Colours, opacity, dashes, icons,
 * tooltips and links are deliberately absent. A diagram inserted on the canvas
 * arrives in Bava's own style (decided 2026-09-19), and leaving D2's palette
 * out of this contract is what keeps that true: nothing downstream can come to
 * depend on it.
 * 
 * The SVG in the same result is for previewing. These two never disagree,
 * because both come from the one compile.
 */
export interface Layout {
    "shapes": LayoutShape[] | null;
    "connections": LayoutConnection[] | null;
}

/**
 * LayoutConnection is one edge, with the route the engine chose.
 */
export interface LayoutConnection {
    "id": string;
    "src": string;
    "dst": string;
    "srcArrow"?: string;
    "dstArrow"?: string;
    "label"?: string;
    "route": LayoutPoint[] | null;
}

export interface LayoutPoint {
    "x": number;
    "y": number;
}

/**
 * LayoutShape is one node, in diagram coordinates.
 */
export interface LayoutShape {
    /**
     * ID is D2's absolute id, dotted for a nested shape ("backend.compile").
     */
    "id": string;

    /**
     * Type is D2's shape name; the frontend maps it to Bava's shape set.
     */
    "type": string;

    /**
     * Parent is the container this shape sits in, or "" at the top level.
     */
    "parent"?: string;
    "x": number;
    "y": number;
    "w": number;
    "h": number;
    "label"?: string;
}

/**
 * Options selects how a diagram is rendered. It is an options struct rather
 * than a widening parameter list because every field here crosses the IPC
 * boundary, and adding one must not change the binding's signature.
 */
export interface Options {
    /**
     * Engine names the layout algorithm. Empty selects layout.DefaultEngine.
     */
    "engine": string;

    /**
     * Theme carries the diagram colours. Nil renders D2's own defaults, which
     * is what every golden committed before theming was added expects.
     */
    "theme"?: Theme | null;
}

/**
 * Result is the whole response to a render request.
 */
export interface Result {
    /**
     * SVG is the rendered diagram, with no XML declaration so it can be
     * injected directly into the DOM node the canvas owns. Empty when the
     * source did not compile.
     */
    "svg": string;

    /**
     * Errors carries compile diagnostics. A failed compile is an expected
     * state, not a failed call: the caller keeps the last good diagram on
     * screen and shows these.
     */
    "errors": Diagnostic[] | null;

    /**
     * NodeMap maps SVG element id to the source that produced it.
     */
    "nodeMap": { [_ in string]?: Span } | null;

    /**
     * Layout is the geometry the canvas builds shapes from. Empty when the
     * source did not compile.
     */
    "layout": Layout;
}

/**
 * Span locates something in the source.
 * 
 * From and To are offsets in UTF-16 code units, which is how JavaScript and
 * CodeMirror index a document, not byte offsets. Line is 1-indexed; D2's own
 * lines are 0-indexed and the conversion happens here, once, so nothing
 * downstream repeats it.
 */
export interface Span {
    "from": number;
    "to": number;
    "line": number;
}

/**
 * Theme carries the diagram colours for a render.
 * 
 * The token layer in `frontend/src/styles/tokens/_color.scss` is the source of
 * truth for the values; Go holds the mapping onto D2's palette and no copy of
 * the palette itself. A diagram's SVG does not inherit CSS, so a theme change
 * has to travel this path or the canvas keeps the old colours while the chrome
 * changes around it.
 */
export interface Theme {
    "background": string;
    "containerFill": string;
    "nodeFill": string;
    "nodeStroke": string;
    "label": string;
    "edge": string;
    "edgeLabel": string;
}
