// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Diagnostic is one compiler complaint about the source.
 */
export interface Diagnostic {
    "message": string;
    "from": number;
    "to": number;
    "line": number;
}

/**
 * Options selects how a diagram is rendered. It is an options struct rather
 * than a widening parameter list because every field here crosses the IPC
 * boundary, and adding one must not change the binding's signature.
 */
export interface Options {
    /**
     * Engine names the layout algorithm. Empty selects layout.DefaultEngine.
     */
    "engine": string;
}

/**
 * Result is the whole response to a render request.
 */
export interface Result {
    /**
     * SVG is the rendered diagram, with no XML declaration so it can be
     * injected directly into the DOM node the canvas owns. Empty when the
     * source did not compile.
     */
    "svg": string;

    /**
     * Errors carries compile diagnostics. A failed compile is an expected
     * state, not a failed call: the caller keeps the last good diagram on
     * screen and shows these.
     */
    "errors": Diagnostic[] | null;

    /**
     * NodeMap maps SVG element id to the source that produced it.
     */
    "nodeMap": { [_ in string]?: Span } | null;
}

/**
 * Span locates something in the source: byte offsets, plus the 1-indexed line
 * for display. D2's own positions are 0-indexed; the conversion happens here,
 * once, so nothing downstream repeats it.
 */
export interface Span {
    "from": number;
    "to": number;
    "line": number;
}
