// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is a page or folder in a Space.
 */
export interface Entry {
    "name": string;

    /**
     * Path is relative to the Space, with "/" between folders.
     */
    "path": string;
    "kind": string;
}

/**
 * TrashItem is a page or folder in the Trash (docs/file-format.md, "Spaces").
 */
export interface TrashItem {
    "id": string;

    /**
     * Path is where it came from, relative to the Space.
     */
    "path": string;
    "kind": string;
    "deletedAt": string;

    /**
     * Size is its size on disk in bytes; not stored.
     */
    "size": number;
}
