// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as format$0 from "../format/models.js";

/**
 * Attachment is a file of the attachments folder: its name, size in bytes,
 * and date modified (RFC 3339), which is when Bava attached it.
 */
export interface Attachment {
    "name": string;
    "size": number;
    "modified": string;
}

/**
 * Entry is a page or folder in a Space.
 */
export interface Entry {
    "name": string;

    /**
     * Path is relative to the Space, with "/" between folders.
     */
    "path": string;
    "kind": string;
}

/**
 * Hit is one page or folder a search found.
 */
export interface Hit {
    "kind": string;
    "path": string;
    "name": string;
    "folder": string;

    /**
     * Count is every time any typed word appears in the name, the Document
     * and the Canvas.
     */
    "count": number;
    "best": Match;
}

/**
 * Match is where a result is best shown.
 */
export interface Match {
    /**
     * Where is InName, InDocument or InCanvas.
     */
    "where": string;

    /**
     * Text is the line or the element's text, cut around the match; empty
     * for a name.
     */
    "text": string;

    /**
     * Word is the typed word the text holds first, as typed.
     */
    "word": string;

    /**
     * Occurrence counts the times Word appears in the page's Document before
     * this match, capitals ignored, as find in a page counts.
     */
    "occurrence": number;

    /**
     * Element is the canvas element holding the match.
     */
    "element": string;
}

/**
 * OpenPage is the page open in the window, with what it holds now: searched
 * in place of its file, so unsaved words are found. Source is its Document's
 * text (front matter included, no canvas block) and Scene its Canvas.
 */
export interface OpenPage {
    "path": string;
    "source": string;
    "scene": format$0.Scene;
}

/**
 * Template is one of the Space's page templates: its group ("" for none),
 * its name without .md, and its path relative to the Space's root.
 */
export interface Template {
    "group": string;
    "name": string;
    "path": string;
}

/**
 * TrashItem is a page, a folder or an attachment in the Trash
 * (docs/file-format.md, "Spaces").
 */
export interface TrashItem {
    "id": string;

    /**
     * Path is where it came from, relative to the Space.
     */
    "path": string;
    "kind": string;
    "deletedAt": string;

    /**
     * Size is its size on disk in bytes; not stored.
     */
    "size": number;
}
