// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Attachment is a file of the attachments folder: its name, size in bytes,
 * and date modified (RFC 3339), which is when Bava attached it.
 */
export interface Attachment {
    "name": string;
    "size": number;
    "modified": string;
}

/**
 * Entry is a page or folder in a Space.
 */
export interface Entry {
    "name": string;

    /**
     * Path is relative to the Space, with "/" between folders.
     */
    "path": string;
    "kind": string;
}

/**
 * Template is one of the Space's page templates: its group ("" for none),
 * its name without .md, and its path relative to the Space's root.
 */
export interface Template {
    "group": string;
    "name": string;
    "path": string;
}

/**
 * TrashItem is a page, a folder or an attachment in the Trash
 * (docs/file-format.md, "Spaces").
 */
export interface TrashItem {
    "id": string;

    /**
     * Path is where it came from, relative to the Space.
     */
    "path": string;
    "kind": string;
    "deletedAt": string;

    /**
     * Size is its size on disk in bytes; not stored.
     */
    "size": number;
}
